version: '3.8'
services:
  database:
    container_name: mongo-quarkus-job
    image: 'mongo:latest'
    ports:
      - '27117:27017'
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: secret
    networks:
      - my-network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 20s
      retries: 3
      start_period: 10s
  job:
    build:
      context: ./
      dockerfile: ./src/main/docker/Dockerfile.jvm
    image: zevolution/quarkus-job-java17-hexagonal-arch
    container_name: quarkus-job-java17-hexagonal-arch
    ports:
      - '5105:5005'
    depends_on:
      database:
        condition: service_healthy
    links:
      - database
    environment:
      ADDITIONAL_OPTS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005 -Xmx128m -Xms64m -XX:MaxMetaspaceSize=128m"
      TZ: "America/Sao_Paulo"
      MONGODB_STRING_CONNECTION: "mongodb://mongoadmin:secret@database:27017"
    networks:
      - my-network
networks:
  my-network:
    driver: bridge